### ISSUE TITLE
Rails integraion

### ISSUE THREAD

**Issue by schonert** [rage-rb/rage#61] opened 2024-02-15 09:52 UTC
This looks amazing! Great job.

We currently have an existing Rails app with certain requests, with 10-20sec external http requests, that could benefit tremendously from this. 

Would we see the same performance gains by simply mounting the router within the rails router? 

```ruby
# config/routes.rb

Rails.application.routes.draw do
  # Mounts the Rage at the "/blazing_fast" path
  mount OtherRackApp, at: '/blazing_fast'

  # Your regular Rails routes
  # ...
end
```

**Comment by rsamoilov** [comment] 2024-02-15 18:03
Hey @schonert !

Currently, the way to go with an existing Rails app is to have Rage process all HTTP requests instead of Rails. See the detailed guide here - https://github.com/rage-rb/rage/wiki/Rails-integration.

Another option would be to extract some routes into a separate Rack app and run it with `rage s -c blazing_fast.ru`.

**Comment by schonert** [comment] 2024-02-17 13:03
Thanks for getting back to me!

I found the docs - however, was hoping there was a progressive migration until cookies and sessions are supported.

Spinning up an additional app with a different entry and route should not be too big a deal tho.

Are you still actively working on this? And can we somehow help get the final pieces of the puzzle together?

**Comment by rsamoilov** [comment] 2024-02-18 12:02
Yes, I’m actively working on this. There was a pause due to my vacation and then a long period of testing the framework in real-world conditions. 

Cookies and sessions are next on my radar and will be added in the following weeks. 

I’d be happy to answer any questions you have or add features you need to migrate. Feel free to drop me a line at developers@rage-rb.dev.

**Comment by schonert** [comment] 2024-02-20 06:17
Arh nice. And thanks! 

Also, would love to help test things in production 🫶🏻

**Comment by schonert** [comment] 2024-02-22 10:22
I just tried setting up a simple route that takes some inputs and constructs a OpenAI prompt. Timed out each time without any response or logs from Rage. Not sure why and won't have time to dive into it this week. 

We're considering changing strategy and implement our API as a pub/sub with pulling or webhooks - since most of the request will require processing images/video as well as interacting with longer request to different LLM endpoints.

Was hoping this could allow us to simply have a ton of long running requests. However, that might not be the best approach after all.

**Comment by rsamoilov** [comment] 2024-02-22 11:37
> Timed out each time without any response or logs from Rage

What hardware and Ruby version are you using? Do you have a reproducible example?

**Comment by schonert** [comment] 2024-02-22 12:01
Macbook M2 ruby 3.3.0.
Not at the moment - woke up early, couldn't sleep, and decided to sit and have some fun. Went ahead an tried implementing in existing project. I'll share if i decide to take another jab at it :)

**Comment by rsamoilov** [comment] 2024-02-22 12:05
OK, I've heard there are some issues with M2. That's probably it. I will look into it. Thanks!

**Comment by rsamoilov** [comment] 2024-03-19 13:07
Hey @schonert 
Just a small update: I've spun up an M2 instance in AWS but couldn't reproduce the issue. I might still be able to find someone with an M2 machine, but until then I'm blocked.

**Comment by schonert** [comment] 2024-04-11 10:50
Hi again Roman. I just created a new rails app and things are working as expected. There must have been something in the other app that makes it go nuts. Thanks for following up!

I was expecting rage to follow rails logging - is there an easy way to achieve this?

**Comment by rsamoilov** [comment] 2024-04-11 12:38
> I was expecting rage to follow rails logging - is there an easy way to achieve this?

Not really. Rage uses structured logging with one line per request. You can find more information about logging here - https://rage-rb.pages.dev/Rage/Logger.

ActiveRecord logging should be working out-of-the-box in development. If you are looking to log the parameters, you can do so with an explicit `before_action`:

```ruby
if Rails.env.development?
  before_action do
    Rage.logger.debug params
  end
end
```

Also, you can add additional information to request logs by defining the `append_info_to_payload` method, more info here - https://rage-rb.pages.dev/RageController/API#append_info_to_payload-instance_method.

Also, you can have logs formatted in JSON:

```ruby
Rage.configure do
  config.log_formatter = Rage::JSONFormatter.new
end
```

Hope this helps 😄

**Comment by schonert** [comment] 2024-04-11 19:24
Thanks! Been playing around with it during the day and it's incredibly fast. Well done!

While testing locally I saw ~40k RPS on my M2 (very simple sqlite lookup). When deployed to a VPS i saw 1-8k RPS. Not sure if it's the M2 being a best or the VPS not being as strong. Using the new ARM on hetzner (8 core).

Also I found that inspecting the generator templates quite useful. This little line made the logging output as expected in production mode.
```
config.logger = Rage::Logger.new(STDOUT)
```

I'm starting to realise the downsides of this being API only. Contemplating how I can incorporate some templating to avoid complicating the stack of this simple app.

**Comment by rsamoilov** [comment] 2024-04-11 22:44
Yeah, M2 is a real beast. If your server has 8 cores, you can try to use cluster mode (the `config.server.workers_count` setting). 

What functionality are you looking for in terms of templating?
Adding some basic templating capabilities to the framework should be pretty straightforward, and it’s not something I’m strictly opposed to.

**Comment by schonert** [comment] 2024-04-12 08:03
Ye tried tuning the workers. 

Ideally being able to hook into the rails templating would be awesome. However I could imagine that becoming quite an undertaking with a lot of rabbit holes. 

I'm considering rethinking how I structure this app. Sticking with good old rails and pre-rendering all possible queries and serving them with nginx. Quite unique for this app - but the data is not that dynamic. 

Was hoping for a higher throughput with rage however I think I/O has become the bottleneck since my current example does a single SQLite query.

**Comment by rsamoilov** [comment] 2024-04-12 22:21
If I add templating to the framework, it's likely gonna be something very basic - probably without partials or implicit rendering.

**Comment by schonert** [comment] 2024-04-13 17:49
> If I add templating to the framework, it's likely gonna be something very basic - probably without partials or implicit rendering.

Yea - would make sense 👍🏻

**Comment by schonert** [comment] 2024-05-22 12:57
@rsamoilov just saw you managed to add `Rage.multi_application` - awesome!
Planing on migrating our public facing API to Rage while the main app runs as usual on Rails. Not sure how to configure routes when running `multi_application`. Will rage use the defined rails routes or should we defined both rage and rails routes?

**Comment by rsamoilov** [comment] 2024-05-22 22:22
Hey @schonert ,

All you need to do with routes is to make sure you use `Rage.routes.draw` instead of `Rails.application.routes.draw`. Rage will parse it to be able to route the requests between the Rails and Rage applications and will then send the route definitions to Rails too. 
You can verify by running the `rails routes` command. 

Feel free to ping me if you encounter any issues.

**Comment by schonert** [comment] 2024-05-24 05:07
Arh so simply replacing the rails router will do the trick! I'll give it a go later today - thanks!

**Comment by rsamoilov** [comment] 2024-05-24 10:15
You should only start the rage server.

You would first perform the regular integration steps (require `rage/rails`, use `Rage.routes.draw`, and launch the server using `rage s` instead of `rails s`). If you then update your API controllers to use Rage, leave Rails controllers intact, and use `Rage.multi_application` in your `config.ru` file, you should be able to use your application the same way you used it before.

Under the hood, Rage will process API requests and proxy Rails requests to the Rails application.

**Comment by schonert** [comment] 2024-05-24 11:09
Hmm... The simple endpoint was working however when i loaded the app i kept getting the route was not found.

Thinking about it I think the errors might have come from the routes not matching. I was unable to setup a wildcard fallback route, (since this is a SPA anything not matched should just load the home.erb.html).

Are wildcards supported?

**Comment by rsamoilov** [comment] 2024-05-24 11:56
Yes, wildcards are supported if in the last section of the path and are not named.

Examples:

```ruby
get "*", to: "..."
get "photos/*", to: "..."
get "/photos/all/*", to: "..."
```

Rage will usually raise an exception if it can't parse your routes file.

**Comment by rsamoilov** [comment] 2024-06-05 10:12
Hey @schonert 

Have you figured this out? Anything I could help with?

Also, feel free to check out v1.5.1, as it fixes another 404 issue.

**Comment by rsamoilov** [comment] 2024-08-23 18:16
Hey @schonert, I'm going to close this, but I hope to see you back with comments, suggestions, or requests 😄

**Closed by rsamoilov** 2024-08-23 18:16 UTC
